name: 🤖 Run renovate
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */10 * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    env:
      LOG_LEVEL: info
      RENOVATE_CONFIG_FILE: default.json
      RENOVATE_TOKEN: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.67.3
      - uses: taiga-family/ci/actions/setup/variables@v1.67.3
      - uses: taiga-family/ci/actions/setup/node@v1.67.3
      - run: |
          npx renovate --print-config \
                       --autodiscover=true \
                       --autodiscover-filter=taiga-family/ng-web-apis
