name: 🤖 Auto update dependencies by Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * MON-FRI"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: renovatebot/github-action@89c8a9b60f5bc8395658abab8f40f96e4b490ebf # v39.1.0
        with:
          renovate-version: full
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
          configurationFile: renovate.json
        env:
          LOG_LEVEL: "debug"
