name: ⚙️ Lint
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: taiga-family/ci/./.github/actions/variables@1.2.0
      - uses: taiga-family/ci/./.github/actions/setup-node@1.2.0

      - name: Lint check
        run: |
          npm run prettier -- --check

concurrency:
  group: lint-${{ github.head_ref }}
  cancel-in-progress: true
